# Generated by Django 5.1 on 2024-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_project_budgeted_resources_projectbudget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='period',
        ),
        migrations.AddField(
            model_name='project',
            name='start_month',
            field=models.CharField(default='Jan 2024', max_length=20),
            preserve_default=False,
        ),
    ]
