# Generated by Django 5.1 on 2024-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_project_period_project_start_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='period',
            field=models.CharField(max_length=20),
        ),
    ]
