# Generated by Django 5.1 on 2024-10-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_project_actual_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_resources', to='app.projectbudget')),
            ],
            options={
                'unique_together': {('project_budget', 'employee')},
            },
        ),
    ]
