# Generated by Django 5.1 on 2024-10-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employeeresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeresource',
            name='allocation_ratio',
            field=models.CharField(max_length=10),
        ),
    ]
